### PR TITLE
CMake 3.13 refactoring

### PR DESCRIPTION
**Pull request by mtarral**
- bump to CMake 3.13 (Debian Buster)
- move driver specific cmake code into `libvmi/driver/xxx/CMakeLists.txt`
- cleanup `libvmi/CMakeLists.txt`

### CODE REVIEW

**Comment by mtarral** [comment]
@tklengyel what do you think about bumping CMake version to `3.13` ? (Debian Buster)

It cleans up the main `libvmi/CMakeLists.txt` by moving the driver specific code into their own CMakeLists.

If you are okay with this, i need to figure out how to install it on Ubuntu 18.04 (CMake 3.12.4).

**Comment by mtarral** [comment]
At the beginning I just wanted to solve the undefined references raised by Travis:
https://travis-ci.org/libvmi/libvmi/jobs/648505505#L456

And I ended up refactoring the code :)

**Comment by mtarral** [comment]
I found the `CMP0079` policy.
When activated, it behaves like CMake `3.13`'s default.

So we don't have to update all the travis tests

**Comment by mtarral** [comment]
> Policy "CMP0079" is not known to this version of CMake.

So this policy works only from 3.13.

**Comment by tklengyel** [comment]
SGTM

**Pull request closed without merging**
